# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# compile C with /usr/bin/cc
C_FLAGS = -static -Wall -Wextra -W -Wdeclaration-after-statement -Wwrite-strings -Wlogical-op -Wshadow

C_DEFINES =

C_INCLUDES = -I/builder/mbedtls-2.7.5/include

